### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by s-v-o** [lars-berger/GlazeWM#236] opened 2023-02-02 09:43 UTC
With the actual release I experience sometimes an unhandled exception:
![image](https://user-images.githubusercontent.com/64085779/216287171-0b8cb0ad-acf8-44ce-bbcd-88a953f1cf22.png)

After that I have to kill and restart GlazeWM. 

See also the attached errors.log

I don't know how to reproduce this at the moment, but it happens from time to time (several times in a week).

If I can provide more information, please don't hesitate to ask and guide me how.

GlazeWM Version: 1.11.0
OS: Windows 11
errors.log: [errors.log](https://github.com/lars-berger/GlazeWM/files/10567437/errors.log)
config.yaml: [config.yaml.txt](https://github.com/lars-berger/GlazeWM/files/10567641/config.yaml.txt)

**Comment by lars-berger** [comment] 2023-02-02 09:52
Have you got `general.cursor_follows_focus` enabled? It's not officially released just yet because it errors occasionally with a very similar stacktrace

**Comment by s-v-o** [comment] 2023-02-02 10:02
No, in the past I have experimented with the standard windows variant. 
But I don't use it at the moment.
I will also attach my config file to the above description .

**Comment by lars-berger** [comment] 2023-02-02 11:22
It's erroring in `SetNativeFocusHandler` but the problem is some other command is calling it with invalid arguments (which doesn't show up in the stacktrace)

Merged in #237 just now for adding the last 15 command invokes so we can see what command is calling `SetNativeFocusCommand` with wrong arguments. are you ok with building off master and seeing if it pops up again? Then we should have way better info to go off of 👌

**Comment by s-v-o** [comment] 2023-02-02 13:30
Ok, I build with this command:
`dotnet build GlazeWM.Bootstrapper/GlazeWM.Bootstrapper.csproj /property:GenerateFullPaths=true --configuration=Release --self-contained -p:IncludeAllContentForSelfExtract=true /consoleloggerparameters:NoSummary --runtime=win-x64 -p:PublishSingleFile=true`
and run the resulting `bin/Release/net6.0-windows/win-x64/GlazeWM.exe`

Correct?

**Comment by lars-berger** [comment] 2023-02-02 14:01
@s-v-o Yeah that should work 👍

**Comment by notblam** [comment] 2023-02-03 02:11
Do you play games or use full screen applications a lot?  Anything in particular that you are doing or running when this error happens?

**Comment by s-v-o** [comment] 2023-02-03 08:07
No, just office applications and developer tools (browser, vscode, eclipse, teams, terminal, sap).
I think it happens most of the time after I start GlazeWM and sort the windows I want to  use. 
Hopefully I could reproduce and send the more verbose error.log, but as I'm running on the latest master it hasn't happened again (of course).

**Closed** 2023-02-06 13:08 UTC
