### ISSUE TITLE
Moving an app to other workspace closes the app

### ISSUE THREAD

**Issue by AgusArdizzone** [lars-berger/GlazeWM#137] opened 2022-09-19 19:03 UTC
Hi!

In the latest build, when there's just one app in a workspace and it gets moved to another workspace, the app gets closed. This occurs when moving the app with alt + shift + workspace , but just when is in the same monitor (moving it with the said shortcut or with {j, l} to other monitor does not cause the app to close).

OS Version: Windows 11 22H2 (Build 22622.598)

**Comment by lars-berger** [comment] 2022-09-19 19:27
Able to reproduce the issue 👍  There's definitely something pretty funky stuff going on with the `move to workspace <NAME>` command right now.

Will try to get a fix out in the next day or two.

**Comment by lars-berger** [comment] 2022-09-21 17:40
Alright pushed a fix to master that should take care of this.

Just to clarify - were you building from source or were you running the [1.7.1 release](https://github.com/lars-berger/GlazeWM/releases/tag/v1.7.1) executable? Because I could reproduce the issue after [this commit](https://github.com/lars-berger/GlazeWM/commits/b9dd41cf0653dd98f3848dc13affa993034ad083) on master, but this is after the 1.7.1 release. Hopefully we're talking about the same issue 👌

**Comment by AgusArdizzone** [comment] 2022-09-21 22:57
I was building from source, so i think we are on the same page 😅

**Comment by lars-berger** [comment] 2022-09-22 07:03
Alright sweet, will go ahead and close this then.

**Closed by lars-berger** 2022-09-22 07:03 UTC
Labels: bug
