### ISSUE TITLE
Keybinding does not work if the window is not selected

### ISSUE THREAD

**Issue by BashkaMen** [lars-berger/GlazeWM#107] opened 2022-08-21 23:26 UTC
Hello, thanks fo this app.

if i clicked on top bar and try to swith work space or use other hotkeys - hotkeys doesn't work

**Comment by lars-berger** [comment] 2022-09-04 11:09
This is a regression after #89, and it's a little tricky to fix.

The current behavior is that keybindings will fire if a managed window has focus. This check was added because of #64.

I think the best behavior would be to keep track of ignored windows (ie. windows where `ignore` command has been invoked). Then, when a user triggers a keybinding, stop it from firing if the currently focused window is in that list of ignored windows.

**Comment by lars-berger** [comment] 2022-10-13 09:03
This has been fixed in the [latest release](https://github.com/lars-berger/GlazeWM/releases)! 🎉

**Closed by lars-berger** 2022-10-13 09:03 UTC
Labels: bug
