### ISSUE TITLE
Random closing/crashing

### ISSUE THREAD

**Issue by nascentt** [lars-berger/GlazeWM#69] opened 2022-05-05 14:11 UTC
Have noticed the program seems to close itself every couple of hours. Not sure how to diagnose, I thought I saw it save to an error log file in the program directory before but am not seeing one now.

Completely possible something I've changed in the yaml or so something I do. But would be good to troubleshoot.

Relaunching program works and thanks to it handling minimized windows well isn't an issue. But might as well diagnose if I can.

**Comment by scubamount** [comment] 2022-05-06 14:41
Hey @nascentt I would love to check out the log.
`C:\Users\%USERNAME%\.glaze-wm\errors.log` should be a good place to look. 
I have been able to induce crashes by opening a ton of windows and hitting my face against the keyboard at the speed of light, but I cannot replicate crashes after a certain time. 
Would you mind including any custom `config.yaml` suspects and I can try them out?

**Comment by lars-berger** [comment] 2022-05-06 15:10
There seems to be an issue with the latest release after changing the handling of minimized windows. It seems to be related windows that minimize to tray when closed (eg. Slack, Discord). If it's the same issue that you're experiencing, one way to reproduce the crash is by visiting a Discord invite link ([like this](https://discord.com/invite/code)). Will try to get a fix out ASAP, but if it's too disruptive right now, you can run the v1.3.0 release in the meantime.

Like @scubamount  mentioned, it'd be great to see the error logs just to double check that it's the same issue.

**Comment by lars-berger** [comment] 2022-05-06 15:59
Put out a [new release](https://github.com/lars-berger/GlazeWM/releases) that should hopefully fix the issue 👍  Would still be worthwhile checking the logs to be sure it's the same crash.

**Comment by nascentt** [comment] 2022-05-07 12:26
> Put out a [new release](https://github.com/lars-berger/GlazeWM/releases) that should hopefully fix the issue 👍 Would still be worthwhile checking the logs to be sure it's the same crash.

error log is here: [errors.log](https://github.com/lars-berger/GlazeWM/files/8645132/errors.log)

Interestingly it seems exactly hourly.

Really doubt that would be the config, but i'll attach anyway: 
[config.zip](https://github.com/lars-berger/GlazeWM/files/8645137/config.zip)

**Comment by nascentt** [comment] 2022-05-07 12:27
> There seems to be an issue with the latest release after changing the handling of minimized windows. It seems to be related to windows that minimize to tray when closed (eg. Slack, Discord). If it's the same issue that you're experiencing, one way to reproduce the crash is by visiting a Discord invite link ([like this](https://discord.com/invite/code)). Will try to get a fix out ASAP, but if it's too disruptive right now, you can run the v1.3.0 release in the meantime.

I am using slick on the computer that's crashing and not using slack on the computer that's not crashing so this makes sense

**Comment by lars-berger** [comment] 2022-05-07 13:57
Ah perfect, that's the same error I was getting with Discord previously. Will close this.

**Closed by lars-berger** 2022-05-07 13:57 UTC
